//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrucksUpFoAdmin.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruksupFOMobileNavigator
    {
        public long MNID { get; set; }
        public string USER_TYPE { get; set; }
        public string MENU_NAME { get; set; }
        public string REDIRECT_URL { get; set; }
        public Nullable<bool> ACTIVE_FLAG { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<long> MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<int> SEQ_NO { get; set; }
        public string ICON { get; set; }
    }
}
