//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrucksUpFoAdmin.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginToken
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserIP { get; set; }
        public string UserMacAddress { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> TokenValidTill { get; set; }
        public Nullable<bool> TokenExpired { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Creationdate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string PlatformCalledFrom { get; set; }
        public string DeviceId { get; set; }
        public string DeviceName { get; set; }
    }
}
