//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrucksUpFoAdmin.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleInfoMaster
    {
        public long ViId { get; set; }
        public Nullable<long> FovmId { get; set; }
        public string OwnType { get; set; }
        public string VehicleType { get; set; }
        public string Vehiclecapacity { get; set; }
        public Nullable<bool> ActiveFlag { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> VehicleCount { get; set; }
        public string VehicleSize { get; set; }
        public string VehicleOwnType { get; set; }
        public string VehicleRC { get; set; }
        public string VehicleNum { get; set; }
        public string DriverNum { get; set; }
    }
}
