//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrucksUpFoAdmin.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldOffiecrLocation
    {
        public long Id { get; set; }
        public Nullable<long> FoId { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
