//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrucksUpFoAdmin.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldOfficerMeeting
    {
        public int ScheduledId { get; set; }
        public Nullable<int> FieldOfficerID { get; set; }
        public string FieldOfficerName { get; set; }
        public string BrokerName { get; set; }
        public string MobileNumber { get; set; }
        public string Alternatename { get; set; }
        public string AlternateMobileNo { get; set; }
        public Nullable<bool> BrokerMeet { get; set; }
        public Nullable<bool> LoadGiven { get; set; }
        public string AdditionalComment { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public string Scheduledtime { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<bool> Scheduled { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedAt { get; set; }
        public string Updatedby { get; set; }
        public string BrokerImagePath { get; set; }
        public string UserImagePath { get; set; }
        public string Address { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<bool> GPS { get; set; }
        public Nullable<bool> Insurance { get; set; }
        public Nullable<bool> FastTag { get; set; }
        public Nullable<bool> Sell_BuyTruck { get; set; }
        public Nullable<bool> GIFT { get; set; }
        public string Remarks { get; set; }
        public string RemarksforLoadNotgiven { get; set; }
    }
}
