//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrucksUpFoAdmin.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldOfficerVisitMaster
    {
        public long FovmId { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string EmailId { get; set; }
        public string Address { get; set; }
        public string OwnType { get; set; }
        public string VehicleType { get; set; }
        public string Vehiclecapacity { get; set; }
        public string VehicleCount { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public string VisitTime { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string VisitingCardUrl { get; set; }
        public Nullable<bool> ActiveFlag { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string StickeringStatus { get; set; }
        public string imagewithstickerurl { get; set; }
        public string imagewithownerurl { get; set; }
        public string Company { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string IsMobileVerified { get; set; }
        public string verifytype { get; set; }
        public string BusinessName { get; set; }
        public string CompanyAddress { get; set; }
        public string Location { get; set; }
    }
}
